# inventory.ini
# Ansible inventory pro Bastion a monitorované servery

[bastion]
bastion-ansible ansible_host=192.168.56.20 ansible_user=vagrant ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[monitored_servers]
# Přidej další servery které chceš monitorovat
# server1 ansible_host=192.168.56.30 ansible_user=vagrant

[all:vars]
ansible_python_interpreter=/usr/bin/python3
