# requirements.yml
# Ansible Galaxy collections nutné pro tento projekt
# Instalace: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.zabbix
    version: ">=2.4.0"   # verze podporující Zabbix Agent2 7.0 LTS
